spring.main.web-application-type: none
cj.software.genetics.schedule.client:
  server:
    create-sub-path: /schedule/create
    breed-sub-path: /schedule/breed
  fitness-procedure-mapping:
    labels:
      LATEST: "latest worker"
      STD_DEVIATION: "standard deviation of all workers"
      SQUARED: "squared sum over all priorities"
    column-titles:
      LATEST: "duration / s"
      STD_DEVIATION: "Std deviation / s"
      SQUARED: "Squared / s"